name = "bas_geoplot"
__version__ = "0.1.0"
__description__ = "GeoPlot: BAS AI Lab plotting scripts for internal plotting & visulisation"
__license__ = "MIT"
__author__ = "George Coombs, Jonathan Smith, Samuel Hall, Harrison Abbot - Software Developers\n Jonathan Smith - Technical Lead\n Maria Fox - Project Manager\n George Coombs - Codebase Champion"
__email__ = "amop@bas.ac.uk"
